---
- name: Docker
  hosts: web1
  tasks:
    - name: Pull an image
      community.docker.docker_image:
        name: prom/blackbox-exporter
        source: pull
        pull:
          platform: amd64

    - name: run container
      docker_container:
        name: blackbox
        image: prom/blackbox-exporter