- name: file module
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
          
          