- name: test block
  hosts: all

  tasks:
    - name: block test
      block:
        - name: debug before task failed
          debug:
            msg: 'I execute normally'

        - name: failure
          command: /bin/echo
      rescue:
        - name: test rescue
          debug:
            msg: 'I never execute, due to the above task failing, :-('
      always:
        - name: always debug
          debug:
            msg: "this always excutes"
      when: ansible_facts['distribution'] == "CentOS"