---

- name: install python 3
  hosts: all
  become: yes

  tasks:
    - name: install Python on centos
      yum:
        name:
          - python3
          - python3-devel
          - python3-pip
          - python-setuptools
        state: present
      when: ansible_facts['distribution'] == "CentOS"

    - name: install repositories
      apt_repository:
        repo: "{{ item }}"
        update_cache: true
      with_items:
        - ppa:deadsnakes/ppa
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install Python system packages
      apt:
        name:
          - python3
          - python3-dev
          - python-setuptools
          - python3-pip
          - python3.8-venv
        state: present
        force_apt_get: yes
      when: ansible_facts['distribution'] == "Ubuntu"