- name: install python3 to diffrent OS
  hosts: all
  become: yes

  tasks:
    - include_role: 
        name: install-python

    - include_role:
        name: deploy-code

    - name: start flask app
      shell: nohup ~/flask-ansible-demo/.env/bin/python ~/flask-ansible-demo/wsgi.py&
      register: myoutput
    
    - name: print stdout
      debug:
        var: myoutput